// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooManagement.database;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    partial class ZooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("HabitatId")
                        .HasColumnType("int");

                    b.Property<int?>("KeeperId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("HabitatId");

                    b.HasIndex("KeeperId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 5,
                            HabitatId = 1,
                            KeeperId = 101,
                            Name = "Lion",
                            Species = "Panthera leo"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 10,
                            HabitatId = 1,
                            KeeperId = 102,
                            Name = "Elephant",
                            Species = "Loxodonta africana"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 8,
                            HabitatId = 1,
                            KeeperId = 103,
                            Name = "Giraffe",
                            Species = "Giraffa camelopardalis"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 3,
                            HabitatId = 4,
                            KeeperId = 104,
                            Name = "Penguin",
                            Species = "Spheniscidae"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 6,
                            HabitatId = 3,
                            KeeperId = 105,
                            Name = "Kangaroo",
                            Species = "Macropodidae"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 7,
                            HabitatId = 2,
                            KeeperId = 101,
                            Name = "Tiger",
                            Species = "Panthera tigris"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 4,
                            HabitatId = 2,
                            KeeperId = 102,
                            Name = "Panda",
                            Species = "Ailuropoda melanoleuca"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 5,
                            HabitatId = 1,
                            KeeperId = 103,
                            Name = "Cheetah",
                            Species = "Acinonyx jubatus"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 2,
                            HabitatId = 2,
                            KeeperId = 105,
                            Name = "Koala",
                            Species = "Phascolarctos cinereus"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 12,
                            HabitatId = 2,
                            KeeperId = 104,
                            Name = "Gorilla",
                            Species = "Gorilla"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Habitat", b =>
                {
                    b.Property<int>("HabitatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitatId"));

                    b.Property<string>("Biotope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HabitatId");

                    b.ToTable("Habitats");

                    b.HasData(
                        new
                        {
                            HabitatId = 1,
                            Biotope = "Grassland",
                            Name = "Savannah"
                        },
                        new
                        {
                            HabitatId = 2,
                            Biotope = "Tropical",
                            Name = "Rainforest"
                        },
                        new
                        {
                            HabitatId = 3,
                            Biotope = "Arid",
                            Name = "Desert"
                        },
                        new
                        {
                            HabitatId = 4,
                            Biotope = "Polar",
                            Name = "Arctic"
                        },
                        new
                        {
                            HabitatId = 5,
                            Biotope = "Temperate",
                            Name = "Forest"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Keeper", b =>
                {
                    b.Property<int>("KeeperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeeperId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Responsibility")
                        .HasColumnType("int");

                    b.HasKey("KeeperId");

                    b.ToTable("Keepers");

                    b.HasData(
                        new
                        {
                            KeeperId = 101,
                            Name = "John Doe",
                            Responsibility = 8
                        },
                        new
                        {
                            KeeperId = 102,
                            Name = "Jane Smith",
                            Responsibility = 5
                        },
                        new
                        {
                            KeeperId = 103,
                            Name = "Bob Johnson",
                            Responsibility = 7
                        },
                        new
                        {
                            KeeperId = 104,
                            Name = "Alice Brown",
                            Responsibility = 6
                        },
                        new
                        {
                            KeeperId = 105,
                            Name = "Charlie Davis",
                            Responsibility = 9
                        },
                        new
                        {
                            KeeperId = 106,
                            Name = "Emma White",
                            Responsibility = 4
                        },
                        new
                        {
                            KeeperId = 107,
                            Name = "David Black",
                            Responsibility = 6
                        },
                        new
                        {
                            KeeperId = 108,
                            Name = "Eva Green",
                            Responsibility = 8
                        },
                        new
                        {
                            KeeperId = 109,
                            Name = "Frank Lee",
                            Responsibility = 3
                        },
                        new
                        {
                            KeeperId = 110,
                            Name = "Grace Taylor",
                            Responsibility = 7
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Habitat", "Habitat")
                        .WithMany("Animals")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Keeper", "Keeper")
                        .WithMany("Animals")
                        .HasForeignKey("KeeperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Habitat");

                    b.Navigation("Keeper");
                });

            modelBuilder.Entity("ZooManagement.Models.Habitat", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("ZooManagement.Models.Keeper", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
